In [1]:
from slidingWindow import llm_dataloader
from Processed import read_txt
import torch
from torch.nn import Embedding
import tiktoken

<hr>

In [2]:
# Initialize parameters
raw_text = read_txt(r'E:\Courses\LLMs\LLMs-from-Scratch\ch02-Working with Text Data\data\the-verdict.txt')
tokenizer = tiktoken.get_encoding('gpt2')
max_length = 4
batch_size = 8
stride = max_length 
shuffle = False
drop_last = False
# 
output_dim = 256
vocab_size = 50257 #after use BPE 
token_embedding_layer = Embedding(vocab_size,output_dim) 
context_length = max_length
pos_embedding_layer = Embedding(context_length,output_dim)
# 
dataloader = llm_dataloader(raw_text,tokenizer,batch_size,max_length,stride,shuffle,drop_last)
# 
dataiter = iter(dataloader)
inputs, targets = next(dataiter)

100%|██████████| 1286/1286 [00:00<00:00, 15318.37it/s]


In [3]:
print(f'Token IDs:\n{inputs}\nInput Shape:{inputs.shape}')
print('-*'*20)
print(f'Targets:\n{targets}\n Targets Shape:{targets.shape}')

Token IDs:
tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Input Shape:torch.Size([8, 4])
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
Targets:
tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])
 Targets Shape:torch.Size([8, 4])


<hr>

# Token Embeddings Layer

In [4]:
token_embeddings= token_embedding_layer(inputs)

print(token_embeddings[:2]) # print 2 embedding 
print(token_embeddings.shape)

tensor([[[ 0.5899, -2.2650, -1.0058,  ...,  1.0582, -1.3516, -0.2528],
         [-0.6102,  0.5806,  0.1923,  ..., -0.2797, -0.0393,  0.6880],
         [ 0.1064,  1.1381,  0.0068,  ...,  1.6583,  0.8139, -0.7083],
         [-1.4293, -0.5136,  0.5766,  ...,  2.0875, -1.1991,  0.3011]],

        [[ 0.6475,  0.5380,  0.3378,  ...,  1.6128, -1.2153,  0.0962],
         [-2.0165,  2.0151, -0.9248,  ...,  0.5406,  1.1366, -1.1557],
         [ 0.0129,  0.2496, -0.0598,  ..., -1.8037, -0.2549,  0.8862],
         [-0.6942, -0.0035,  0.4303,  ...,  0.2214,  0.4662,  1.2901]]],
       grad_fn=<SliceBackward0>)
torch.Size([8, 4, 256])


In [5]:
token_embeddings[0][0] # print one raw 

tensor([ 5.8986e-01, -2.2650e+00, -1.0058e+00, -4.0477e-01,  2.3961e-02,
        -8.4919e-01,  2.1994e+00,  1.8230e-01,  1.1145e+00, -6.3978e-01,
         6.5116e-01, -2.7994e-01,  2.4138e-02,  1.0118e+00, -1.7863e+00,
        -3.3997e-01,  2.4021e-01, -8.6360e-01,  1.6234e+00, -6.4908e-01,
        -4.9242e-01,  4.7222e-01,  7.0927e-01, -1.3238e-01, -1.2507e+00,
         1.0185e+00, -4.7168e-01, -4.7430e-01,  2.3675e+00, -9.7850e-03,
         4.4780e-01, -1.2609e+00, -9.2068e-01,  1.9468e-01, -1.1174e+00,
        -1.0782e+00,  3.4360e-01, -1.6371e+00, -8.2822e-01,  1.0826e+00,
         1.0101e+00, -4.1291e-01, -4.3896e-01,  8.3303e-01,  1.9196e+00,
        -1.1700e+00,  1.0673e+00, -3.9927e-02, -1.8670e+00, -8.4616e-01,
         4.8809e-01,  1.2945e+00,  6.5960e-01, -9.0762e-01,  1.6333e+00,
        -1.0016e+00,  4.1135e-01,  4.6505e-01,  7.7219e-02, -3.3204e-01,
         2.4387e-01,  4.3717e-01,  1.3726e+00,  2.0943e-01,  1.7603e-01,
         3.0125e-01, -4.3039e-02,  1.0131e+00,  2.9

<hr>

# Position Embedding Layer

In [6]:
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [7]:
print(pos_embeddings[0])

tensor([ 0.1176,  0.4917,  0.2027,  2.3352,  0.5601,  0.1329,  0.7945, -0.8301,
        -1.4458,  0.2496,  0.6097, -0.3420, -0.5437,  0.6284, -0.7748, -2.3801,
         0.4767, -0.5610,  0.9331,  0.2100, -1.4567,  0.6408,  0.9580, -0.2480,
         1.5920, -0.6674, -0.0573,  0.8251, -0.0382, -2.4458,  1.2393, -0.2022,
         1.4708, -0.6372, -0.6738, -0.2046, -0.4991,  0.6994,  1.3749,  1.0307,
        -1.0226,  0.7088, -2.2867, -0.5230, -0.3672, -1.1590,  0.1260, -1.0807,
        -0.0831,  0.1392,  0.3289,  0.4166,  0.0140,  0.7035,  0.1439, -0.5006,
         0.8507,  0.6613, -0.4725,  1.0842,  0.7901, -1.1069, -0.0389, -0.2469,
        -0.2663, -1.5507, -0.8488,  0.3759,  0.8536,  0.5837,  0.1206, -0.4834,
        -1.8719,  0.8002,  1.0162, -2.0963,  1.2174, -1.4686,  1.2448,  0.6842,
         0.6862,  0.7614,  0.0150,  1.8148, -1.9920,  0.7116, -0.0224, -0.0061,
         0.0950,  0.2777,  0.2102, -0.2983, -1.6750,  1.0517,  0.1830, -0.5232,
        -0.3899, -1.0786, -0.0568, -0.15

<hr>

# Input Embedding 

In [8]:
input_embeddings = token_embeddings + pos_embeddings 
print(input_embeddings.shape)

torch.Size([8, 4, 256])


In [9]:
input_embeddings[0]

tensor([[ 0.7074, -1.7732, -0.8032,  ...,  1.5336, -2.4308, -0.6625],
        [-0.2020,  0.1934,  0.6753,  ..., -2.9168, -1.3860,  0.8789],
        [ 0.5474,  0.6868, -0.0635,  ...,  2.7347,  0.8467, -1.7815],
        [-1.6508, -0.5596, -0.1177,  ...,  3.7795, -2.9219, -1.5049]],
       grad_fn=<SelectBackward0>)