- We are almost there: now let's plug in the transformer block into the architecture we coded at the very beginning of this chapter so that we obtain a usable GPT architecture
- Note that the transformer block is repeated multiple times; in the case of the smallest 124M GPT-2 model, we repeat it 12 times:

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/ch04_compressed/15.webp" width="400px">

In [4]:
from torch import nn
import torch
from TransformerBlock import TransformerBlock
from LayerNorm import LayerNorm

class GPTModel(nn.Module):
  def __init__(self,cfg):
    super().__init__()
    self.tok_emb = nn.Embedding(cfg["vocab_size"],cfg["emb_dim"])
    self.pos_emb = nn.Embedding(cfg["context_length"],cfg["emb_dim"])
    self.dropout_emb = nn.Dropout(cfg["drop_rate"])
    self.transformer_blocks = nn.Sequential( *[TransformerBlock(cfg) for _ in range(cfg["n_layers"])])
    self.final_norm = LayerNorm(cfg["emb_dim"])
    self.out_ff = nn.Linear(cfg["emb_dim"],cfg["vocab_size"],bias = False)
  
  def forward(self, idx):
    batch_size, seq_len = idx.shape
    tok_embeds = self.tok_emb(idx)
    pos_embeds = self.pos_emb(torch.arange(seq_len, device=idx.device))

    x = tok_embeds + pos_embeds
    x = self.dropout_emb(x)
    x = self.transformer_blocks(x)
    x = self.final_norm(x)
    logits = self.out_ff(x)
    return logits



In [6]:
GPT_CONFIG_124M = {
  "vocab_size": 50257,  # Vocabulary size
  "context_length": 1024,  # Context length
  "emb_dim": 768,  # Embedding dimension
  "n_heads": 12,  # Number of attention heads
  "n_layers": 12,  # Number of layers
  "drop_rate": 0.1,  # Dropout rate
  "qkv_bias": False  # Query-Key-Value bias
}
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")

batch = []

txt1 = "Every effort moves you"
txt2 = "Every day holds a"

batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)
print(batch)


tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])


In [7]:
torch.manual_seed(123)
model = GPTModel(GPT_CONFIG_124M)

out = model(batch)
print("Input batch:\n", batch)
print("\nOutput shape:", out.shape)
print(out)

Input batch:
 tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])

Output shape: torch.Size([2, 4, 50257])
tensor([[[-0.0070, -0.2133, -0.3459,  ..., -0.3236, -0.2339, -0.1066],
         [ 0.7062, -0.7423, -0.6639,  ..., -0.6529, -0.1396, -0.2159],
         [ 0.8221, -0.2977, -0.4546,  ...,  0.0913, -0.6947, -0.2085],
         [-0.3930,  0.3073, -0.1347,  ...,  1.0458,  0.4616, -0.5291]],

        [[ 0.1387, -0.4075, -0.1558,  ..., -0.0890, -0.0674, -0.0154],
         [ 0.2354, -0.1174, -0.1306,  ...,  1.0723, -0.3517,  0.3907],
         [ 0.7367,  0.3379, -0.4309,  ...,  0.8462,  0.2214, -0.2534],
         [ 0.0168, -0.0721,  0.3451,  ...,  1.1348, -0.4069,  0.0313]]],
       grad_fn=<UnsafeViewBackward0>)


In [8]:
total_params = sum(p.numel() for p in model.parameters())
print(f"Total number of parameters: {total_params:,}")

Total number of parameters: 163,009,536


- As we see above, this model has 163M, not 124M parameters; why?
- In the original GPT-2 paper, the researchers applied weight tying, which means that they reused the token embedding layer (`tok_emb`) as the output layer, which means setting `self.out_head.weight = self.tok_emb.weight`
- The token embedding layer projects the 50,257-dimensional one-hot encoded input tokens to a 768-dimensional embedding representation
- The output layer projects 768-dimensional embeddings back into a 50,257-dimensional representation so that we can convert these back into words (more about that in the next section)
- So, the embedding and output layer have the same number of weight parameters, as we can see based on the shape of their weight matrices
- However, a quick note about its size: we previously referred to it as a 124M parameter model; we can double check this number as follows:

In [10]:
total_params_gpt2 =  total_params - sum(p.numel() for p in model.out_ff.parameters())
print(f"Number of trainable parameters considering weight tying: {total_params_gpt2:,}")

Number of trainable parameters considering weight tying: 124,412,160


In [11]:
# Calculate the total size in bytes (assuming float32, 4 bytes per parameter)
total_size_bytes = total_params * 4

# Convert to megabytes
total_size_mb = total_size_bytes / (1024 * 1024)

print(f"Total size of the model: {total_size_mb:.2f} MB")

Total size of the model: 621.83 MB
